### ISSUE TITLE
Set attributes are represented as lists

### ISSUE THREAD

**Issue by klukashka** [realkarych/rxconf#74]
**Describe the bug**
Set attributes are unexpectedly stored as list attributes

**To Reproduce**
```
from rxconf.rxconf import RxConf


path = "./tests/resources/primitives.yml"
conf = RxConf.from_file(path)
print(type(conf.set._value))

>>> <class 'list'>
```

**Expected behavior**
Set attributes should be stored as sets and if a user tries to get a type of _value it should return <class 'set'>

**Screenshots**
![image](https://github.com/user-attachments/assets/ea943220-da0e-4515-ae4e-5dc0f49ae3d5)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - OS Version: Ubuntu 22.04.5
 - RxConf Version: 0.0.2

**Additional context**

**Comment by realkarych** [comment]
Not a bug according to https://yaml.org/type/set.html

If we'll set like 
```
set: !!set
  ? a
  ? b
  ? c
```, set will be parsed correctly

But should fix yaml test sources.
