### ISSUE TITLE
Different empty configs representation

### ISSUE THREAD

**Issue by realkarych** [realkarych/rxconf#83]
**Describe the bug**
Now in tests empty config asserts like assert RxConf().
This way of checking caused bug that wasn't detected before.

Bug: different empty config-types has different attributes tree, for example:
empty toml:
AttributeType({})
empty yaml:
AttributeType(None)

**Expected behavior**
All empty configs should be represented as AttributeType(None).

**Desktop (please complete the following information):**
 - RxConf Version 0.0.2

**Comment by klukashka** [comment]
Also it is better to change "empty" tests. Replace 
```
assert conf
```
to
```
assert str(conf) == "AttributeType(None)"
```
